/**
 * Session detail page: stats, timeline, event log.
 * Session ID is read from pathname (/sessions/:id). Netlify rewrites to this page.
 */

import { supabase } from '../supabase.js'
import { initDashboardLayout } from '../dashboard-layout.js'
import { escapeHtml, formatDuration, modeLabel } from '../utils.js'
import { isValidUuid } from '../validators.js'
import { t, getLocale } from '../dashboard-i18n.js'
import { logError } from '../logger.js'
import { track, EVENTS } from '../analytics.js'
import { BASE_PATH } from '../base-path.js'

function eventLabel(type) {
  const labels = {
    present: t('dashboard.sessionDetail.focused', 'Focused'),
    away: t('dashboard.sessionDetail.away', 'Away'),
    gadget_suspected: t('dashboard.sessionDetail.gadget', 'Gadget'),
    screen_distraction: t('dashboard.sessionDetail.screenDistraction', 'Screen distraction'),
    paused: t('dashboard.sessionDetail.paused', 'Paused'),
  }
  return labels[type] || type
}

const EVENT_TYPE_TO_TIMELINE_CLASS = {
  present: 'focused',
  away: 'away',
  gadget_suspected: 'gadget',
  screen_distraction: 'screen',
  paused: 'paused',
}

function getSessionIdFromPath() {
  // Check query param first (GitHub Pages 404.html redirect)
  const params = new URLSearchParams(window.location.search)
  const idParam = params.get('id')
  if (idParam) return idParam
  // Original pathname parsing (Netlify rewrite)
  const path = window.location.pathname
  const segments = path.split('/').filter(Boolean)
  const last = segments[segments.length - 1]
  if (last === 'detail' || !last) return null
  return last
}

function formatTime(iso) {
  if (!iso) return '-'
  const d = new Date(iso)
  if (isNaN(d.getTime())) return '-'
  return d.toLocaleTimeString(getLocale(), { hour: 'numeric', minute: '2-digit', second: '2-digit' })
}

async function fetchSessionWithEvents(sessionId, userId) {
  const { data: session, error: sessionError } = await supabase
    .from('sessions')
    .select('id, session_name, start_time, end_time, monitoring_mode, summary_stats, objective')
    .eq('id', sessionId)
    .eq('user_id', userId)
    .single()
  // PGRST116 = "not found" from .single() - return null instead of throwing
  if (sessionError) {
    if (sessionError.code === 'PGRST116') return { session: null, events: [] }
    throw sessionError
  }
  if (!session) return { session: null, events: [] }

  // Ownership already verified by the session query above (user_id filter on sessions table).
  // Events are scoped to the validated session_id, so no separate user_id filter needed here.
  const { data: events, error: eventsError } = await supabase
    .from('session_events')
    .select('event_type, start_time, end_time, duration_seconds')
    .eq('session_id', sessionId)
    .order('start_time', { ascending: true })
  if (eventsError) throw eventsError

  return { session, events: events || [] }
}

/**
 * Build timeline segments from events. Each segment: { type, durationSeconds, class }.
 */
function buildTimelineSegments(events, totalSeconds) {
  if (!events.length || totalSeconds <= 0) return []
  const segments = []
  for (const e of events) {
    const dur = e.duration_seconds ?? 0
    if (dur <= 0) continue
    const type = e.event_type || 'present'
    segments.push({
      type,
      durationSeconds: dur,
      class: EVENT_TYPE_TO_TIMELINE_CLASS[type] || 'idle',
    })
  }
  return segments
}

function render(main, session, events) {
  const base = BASE_PATH
  const summary = session.summary_stats || {}
  const presentSec = summary.present_seconds ?? 0
  const awaySec = summary.away_seconds ?? 0
  const gadgetSec = summary.gadget_seconds ?? 0
  const screenSec = summary.screen_distraction_seconds ?? 0
  const pausedSec = summary.paused_seconds ?? 0
  const totalActive = presentSec + awaySec + gadgetSec + screenSec
  const totalSec = totalActive + pausedSec
  const focusRate = totalActive > 0 ? Math.round((presentSec / totalActive) * 100) : 0

  const segments = buildTimelineSegments(events, totalSec)
  const segmentWidths = totalSec > 0 ? segments.map((s) => (s.durationSeconds / totalSec) * 100) : []

  const startDate = new Date(session.start_time)
  const dateStr = startDate.toLocaleDateString(getLocale(), { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })
  // Use session_name (auto-generated by desktop app)
  const displayTitle = session.session_name || `${t('dashboard.common.session', 'Session')} ${startDate.toLocaleTimeString(getLocale(), { hour: 'numeric', minute: '2-digit' })}`

  main.innerHTML = `
    <a href="${base}/sessions/" class="dashboard-back-link">${t('dashboard.common.backToSessions', 'Back to Sessions')}</a>
    <h1 class="dashboard-page-title">${escapeHtml(displayTitle)}</h1>
    ${session.objective ? `<p class="dashboard-page-subtitle">${escapeHtml(session.objective)}</p>` : ''}
    <p class="dashboard-page-subtitle">
      ${dateStr} &middot; ${modeLabel(session.monitoring_mode)}
    </p>

    <div class="dashboard-stat-cards dashboard-stat-cards--2col">
      <div class="dashboard-stat-card">
        <div class="dashboard-stat-card-label">${t('dashboard.sessionDetail.focusLabel', 'Focus')}</div>
        <div class="dashboard-stat-card-value">${formatDuration(presentSec)}</div>
      </div>
      <div class="dashboard-stat-card">
        <div class="dashboard-stat-card-label">${t('dashboard.sessionDetail.awayLabel', 'Away')}</div>
        <div class="dashboard-stat-card-value">${formatDuration(awaySec)}</div>
      </div>
      <div class="dashboard-stat-card">
        <div class="dashboard-stat-card-label">${t('dashboard.sessionDetail.gadgetsLabel', 'Gadgets')}</div>
        <div class="dashboard-stat-card-value">${formatDuration(gadgetSec)}</div>
      </div>
      <div class="dashboard-stat-card">
        <div class="dashboard-stat-card-label">${t('dashboard.sessionDetail.pausedLabel', 'Paused')}</div>
        <div class="dashboard-stat-card-value">${formatDuration(pausedSec)}</div>
      </div>
    </div>

    <div class="dashboard-section">
      <h2 class="dashboard-section-title">${t('dashboard.sessionDetail.focusRateLabel', 'Focus Rate:')} ${focusRate}%</h2>
      <div class="dashboard-progress-wrap">
        <div class="dashboard-progress-bar">
          <div class="dashboard-progress-fill" style="width: ${focusRate}%;"></div>
        </div>
      </div>
    </div>

    <div class="dashboard-section">
      <h2 class="dashboard-section-title">${t('dashboard.sessionDetail.timeline', 'Timeline')}</h2>
      <div class="dashboard-card">
        ${segments.length === 0
          ? `<p class="dashboard-meta-sub">${t('dashboard.sessionDetail.noEventData', 'No event data for this session.')}</p>`
          : `
          <div class="dashboard-timeline-bar">
            ${segments.map((seg, i) => `
              <div class="dashboard-timeline-segment ${seg.class}" style="width: ${segmentWidths[i]}%;" title="${escapeHtml(seg.type)}"></div>
            `).join('')}
          </div>
          <div class="dashboard-timeline-legend">
            <span><i class="legend-focused"></i> ${t('dashboard.sessionDetail.legendFocused', 'Focused')}</span>
            <span><i class="legend-away"></i> ${t('dashboard.sessionDetail.legendAway', 'Away')}</span>
            <span><i class="legend-gadget"></i> ${t('dashboard.sessionDetail.legendGadget', 'Gadget')}</span>
            <span><i class="legend-screen"></i> ${t('dashboard.sessionDetail.legendScreen', 'Screen')}</span>
            <span><i class="legend-paused"></i> ${t('dashboard.sessionDetail.legendPaused', 'Paused')}</span>
          </div>
          `}
      </div>
    </div>

    <div class="dashboard-section">
      <h2 class="dashboard-section-title">${t('dashboard.sessionDetail.eventLog', 'Event Log')}</h2>
      <div class="dashboard-table-wrap">
        ${events.length === 0
          ? `<p class="dashboard-meta-sub dashboard-table-empty">${t('dashboard.sessionDetail.noEventsRecorded', 'No events recorded.')}</p>`
          : `
          <table class="dashboard-table">
            <thead>
              <tr>
                <th>${t('dashboard.sessionDetail.thStart', 'Start')}</th>
                <th>${t('dashboard.sessionDetail.thEnd', 'End')}</th>
                <th>${t('dashboard.sessionDetail.thType', 'Type')}</th>
                <th>${t('dashboard.sessionDetail.thDuration', 'Duration')}</th>
              </tr>
            </thead>
            <tbody>
              ${events.map((e) => `
                <tr>
                  <td>${formatTime(e.start_time)}</td>
                  <td>${formatTime(e.end_time)}</td>
                  <td>${escapeHtml(eventLabel(e.event_type))}</td>
                  <td>${formatDuration(e.duration_seconds)}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          `}
      </div>
    </div>
  `
}

async function main() {
  const result = await initDashboardLayout()
  if (!result) return

  const sessionId = getSessionIdFromPath()
  if (!sessionId || !isValidUuid(sessionId)) {
    window.location.href = `${BASE_PATH}/sessions/`
    return
  }

  const mainEl = document.querySelector('.dashboard-main')
  if (!mainEl) return

  mainEl.innerHTML = `<div class="dashboard-loading"><div class="dashboard-spinner"></div><p>${t('dashboard.sessionDetail.loading', 'Loading session...')}</p></div>`

  try {
    const { session, events } = await fetchSessionWithEvents(sessionId, result.user.id)
    if (!session) {
      mainEl.innerHTML = `
        <div class="dashboard-empty">
          <p class="dashboard-empty-title">${t('dashboard.sessionDetail.notFound', 'Session not found')}</p>
          <p><a href="${BASE_PATH}/sessions/">${t('dashboard.common.backToSessions', 'Back to Sessions')}</a></p>
        </div>
      `
      return
    }
    render(mainEl, session, events)
    track(EVENTS.SESSION_DETAIL_VIEWED, { monitoring_mode: session.monitoring_mode })
  } catch (err) {
    logError('Session detail load failed:', err)
    mainEl.innerHTML = `
      <div class="dashboard-empty">
        <p class="dashboard-empty-title">${t('dashboard.sessionDetail.errorTitle', 'Could not load session')}</p>
        <p>${t('dashboard.common.tryAgain', 'Please try again.')}</p>
        <p><a href="${BASE_PATH}/sessions/">${t('dashboard.common.backToSessions', 'Back to Sessions')}</a></p>
      </div>
    `
  }
}

main()
