/**
 * Session history list: paginated (20 per page), newest first.
 */

import { supabase } from '../supabase.js'
import { initDashboardLayout } from '../dashboard-layout.js'
import { escapeHtml, formatDuration, modeLabel, focusLevelClass } from '../utils.js'
import { t, getLocale } from '../dashboard-i18n.js'
import { logError } from '../logger.js'
import { BASE_PATH } from '../base-path.js'

const PAGE_SIZE = 20

async function fetchSessionsWithCount(page, userId) {
  const from = (page - 1) * PAGE_SIZE
  const to = from + PAGE_SIZE - 1
  const { data, error, count } = await supabase
    .from('sessions')
    .select('id, session_name, start_time, end_time, monitoring_mode, summary_stats, objective', { count: 'exact', head: false })
    .eq('user_id', userId)
    .order('start_time', { ascending: false })
    .range(from, to)
  if (error) throw error
  return { sessions: data || [], total: count ?? 0 }
}

function render(main, sessions, page, total, goToPage) {
  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE))
  const base = BASE_PATH

  main.innerHTML = `
    <h1 class="dashboard-page-title">${t('dashboard.sessionList.title', 'Session History')}</h1>

    <div class="dashboard-card">
      ${sessions.length === 0
        ? `
        <div class="dashboard-empty">
          <p class="dashboard-empty-title">${t('dashboard.sessionList.noSessionsTitle', 'No sessions yet')}</p>
          <p>${t('dashboard.sessionList.noSessionsDesc', 'Complete a session with the BrainDock desktop app to see your history here.')}</p>
        </div>
        `
        : `
        <ul class="dashboard-list">
          ${sessions.map((s) => {
            const summary = s.summary_stats || {}
            const duration = summary.present_seconds ?? 0
            const pct = summary.focus_percentage ?? 0
            const gadgets = summary.gadget_count ?? 0
            const screen = summary.screen_distraction_count ?? 0
            const start = new Date(s.start_time)
            const dateStr = start.toLocaleDateString(getLocale(), { month: 'long', day: 'numeric', year: 'numeric' })
            // Use session_name (auto-generated by desktop app)
            const name = s.session_name || `${t('dashboard.common.session', 'Session')} ${start.toLocaleTimeString(getLocale(), { hour: 'numeric', minute: '2-digit' })}`
            const activeSec = summary.active_seconds ?? ((summary.present_seconds ?? 0) + (summary.away_seconds ?? 0) + (summary.gadget_seconds ?? 0) + (summary.screen_distraction_seconds ?? 0))
            return `
              <li class="dashboard-list-item ${focusLevelClass(Math.round(pct))}">
                <div>
                  <strong>${escapeHtml(name)}</strong>${s.objective ? `<br><span class="dashboard-meta">${escapeHtml(s.objective)}</span>` : ''}<br>
                  <span class="dashboard-meta">${dateStr}</span><br>
                  <span class="dashboard-meta">${modeLabel(s.monitoring_mode)} &middot; ${formatDuration(activeSec)} ${t('dashboard.common.active', 'active')} &middot; ${Math.round(pct)}% ${t('dashboard.common.focus', 'focus')}</span><br>
                  <span class="dashboard-meta-sub">${gadgets} ${t('dashboard.common.gadgets', 'gadgets')} &middot; ${screen} ${t('dashboard.common.screenDistractions', 'screen distractions')}</span>
                </div>
                <a href="${base}/sessions/${escapeHtml(s.id)}" class="btn btn-secondary dashboard-btn-sm">${t('dashboard.actions.view', 'View')}</a>
              </li>
            `
          }).join('')}
        </ul>

        <div class="dashboard-pagination">
          <button type="button" id="sessions-prev" ${page <= 1 ? 'disabled' : ''}>${t('dashboard.actions.previous', 'Previous')}</button>
          <span>${t('dashboard.common.page', 'Page')} ${page} ${t('dashboard.common.of', 'of')} ${totalPages}</span>
          <button type="button" id="sessions-next" ${page >= totalPages ? 'disabled' : ''}>${t('dashboard.actions.next', 'Next')}</button>
        </div>
        `}
    </div>
  `

  const prevBtn = main.querySelector('#sessions-prev')
  const nextBtn = main.querySelector('#sessions-next')
  if (prevBtn) prevBtn.addEventListener('click', () => goToPage(page - 1))
  if (nextBtn) nextBtn.addEventListener('click', () => goToPage(page + 1))
}

async function main() {
  const result = await initDashboardLayout()
  if (!result) return

  const mainEl = document.querySelector('.dashboard-main')
  if (!mainEl) return

  let currentPage = 1

  const userId = result.user.id

  async function loadPage(page) {
    currentPage = page
    mainEl.innerHTML = `<div class="dashboard-loading"><div class="dashboard-spinner"></div><p>${t('dashboard.sessionList.loading', 'Loading sessions...')}</p></div>`
    try {
      const { sessions, total } = await fetchSessionsWithCount(page, userId)
      render(mainEl, sessions, page, total, loadPage)
    } catch (err) {
      logError('Sessions list load failed:', err)
      mainEl.innerHTML = `
        <div class="dashboard-empty">
          <p class="dashboard-empty-title">${t('dashboard.sessionList.errorTitle', 'Could not load sessions')}</p>
          <p>${t('dashboard.common.tryAgain', 'Please try again.')}</p>
        </div>
      `
    }
  }

  await loadPage(1)
}

main()
